version: "3"

volumes:
  postgis-data:

services:

  api:
    image: geopython/pygeoapi:latest
    ports:
      - "5000:80"
    volumes:
      - ./pygeoapi-config.yml:/pygeoapi/local.config.yml
      - ./data:/data
    depends_on:
      - "postgres"
    restart: on-failure

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"

  postgres:
    image: kartoza/postgis:12.0
    volumes:
      - postgis-data:/var/lib/postgresql
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - POSTGRES_DB=gis
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - ALLOW_IP_RANGE=0.0.0.0/0
      # Add extensions you need to be enabled by default in the DB. Default are the three specified below
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology
    ports:
      - "5432:5432"
