version: "3"

volumes:
  postgis-data:

services:

  api:
    image: geopython/pygeoapi:latest
    ports:
      - "5000:80"
    volumes:
      - ./pygeoapi-config.yml:/pygeoapi/local.config.yml
      - ./data:/data

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
