server:
  bind:
    host: 0.0.0.0
    port: 80
  url: http://localhost:5000
  mimetype: application/json; charset=UTF-8
  encoding: utf-8
  language: en-US
  cors: true
  pretty_print: true
  limit: 10
  map:
    url: https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}.png
    attribution: <a href="https://wikimediafoundation.org/wiki/Maps_Terms_of_Use">Wikimedia
      maps</a> | Map data &copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap
      contributors</a>

logging:
  level: ERROR

metadata:
  identification:
    title: KWIS
    description: A set of regional climate change and mitigation datasets
    keywords:
    - climate
    - regional
    - api
    keywords_type: theme
    terms_of_service: None
    url: https://github.com/lhm/kwis
  license:
    name: CC-BY 4.0 license
    url: https://creativecommons.org/licenses/by/4.0/
  provider:
    name: Lars
    url: https://github.com/lhm
  contact:
    name: Lars
    city: Leipzig
    stateorprovince: Saxony
    country: Germany
    email: none@example.com

datasets:

  districts:
    title: German Landkreise
    description: Administrative boundaries
    keywords:
    - Germany
    - Administrative
    - Boundaries
    links:
    - type: text/html
      rel: canonical
      title: information
      href: https://gdz.bkg.bund.de/index.php/default/digitale-geodaten/verwaltungsgebiete/verwaltungsgebiete-1-250-000-ebenen-stand-01-01-vg250-ebenen-01-01.html
      hreflang: de-DE
    extents:
      spatial:
        bbox: [-180, -90, 180, 90]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
      temporal:
        begin: 2007-01-01
        end: null # or empty
    provider:
      name: SQLiteGPKG
      data: /data/districts.gpkg
      id_field: fid
      table: districts

  prtr_emissions:
    title: German PRTR Emissions
    description: German Emissions from the PRTR Register
    keywords:
    - Germany
    - Emissions
    - PRTR
    links:
    - type: text/html
      rel: canonical
      title: information
      href: https://www.thru.de/
      hreflang: de-DE
    extents:
      spatial:
        bbox: [-180, -90, 180, 90]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
      temporal:
        begin: 2007-01-01
        end: 2017-12-31
    provider:
      name: SQLiteGPKG
      data: /data/prtr_emissions.gpkg
      id_field: fid
      table: prtr_emissions
